version: '3.4'

x-explorer:
  &explorer
    build:
      context: .
    image: explorer
    expose:
     - 8080
    ports:
      - 8019:8000
    volumes:
      - ./node_modules:/var/explorer/node_modules
    restart: always

services:
  explorer:
    << : *explorer